Internal change
googleapis/google-cloudevents pull request #144
Opened 2021-01-22 19:16 UTC by jay-shi

Internal change

2021-01-22 19:27 UTC, jay-shi commented
This is just a test commit to test copybara service. Do not approve.

2021-01-22 19:46 UTC, grant requested changes

2021-01-22 19:46 UTC, grant commented on proto/google/events/cloud/audit/v1/data.proto
> -option csharp_namespace = "Google.Events.Protobuf.Cloud.Audit.V1";
We can't remove this or the generator will break

2021-01-25 18:22 UTC, grant approved these changes

2021-01-25 18:22 UTC, grant commented on proto/google/events/cloud/audit/v1/data.proto
> -option csharp_namespace = "Google.Events.Protobuf.Cloud.Audit.V1";
Comment looks outdated.

2021-01-29 02:26 UTC, jay-shi commented
It's just a test PR.

2021-01-29 02:26 UTC, closed without merging