Create StorageObjectDataWorkflows-simple
googleapis/google-cloudevents pull request #311
Opened 2022-01-05 01:14 UTC by minyu19

Add sample data file for Eventarc

2022-01-12 12:30 UTC, grant requested changes

2022-01-12 12:30 UTC, grant commented on testdata/google/events/cloud/storage/v1/StorageObjectDataWorkflows-simple
> +{
- File must end with `.json`
- Just include the contents of `data`

2022-01-14 19:24 UTC, minyu19 reviewed
Thank you, Grant. I have updated the file as suggested.

2022-01-14 22:49 UTC, grant approved these changes
Ensure there is 2 space indentation. Approved

2022-01-20 19:51 UTC, ace-n approved these changes

2022-01-27 19:36 UTC, grant commented
It looks like the CI: `Generate / build (pull_request)` is failing.

Looking into the CI logs, it shows the filename is invalid.

The filename for test data should be something like:

`testdata/google/events/cloud/storage/v1/StorageObjectData-workflows.json`

---

See https://github.com/googleapis/google-cloudevents/blob/main/testdata/README.md#test-data

2022-01-27 19:39 UTC, grant commented
Also would be good to add this to the registry:

https://github.com/googleapis/google-cloudevents/blob/main/jsonschema/google/events/cloud/storage/v1/StorageObjectData.json

See failing `Generate / build (pull_request)` logs:

```
b/jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
@@ -3,7 +3,8 @@
   "name": "StorageObjectData",
   "examples": [
     "https://googleapis.github.io/google-cloudevents/testdata/google/events/cloud/storage/v1/StorageObjectData-complex.json",
-    "https://googleapis.github.io/google-cloudevents/testdata/google/events/cloud/storage/v1/StorageObjectData-simple.json"
+    "https://googleapis.github.io/google-cloudevents/testdata/google/events/cloud/storage/v1/StorageObjectData-simple.json",
+    "https://googleapis.github.io/google-cloudevents/testdata/google/events/cloud/storage/v1/StorageObjectDataWorkflows-simple.json"
   ],
```

2022-02-04 16:50 UTC, minyu19 commented
This change had been initially suggested to refer to in the documentation. Later on, it was decided to add the appropriate examples to a different folder for documentation: https://github.com/googleapis/google-cloudevents/tree/main/examples. Since the samples have been added to the examples folder, I'm closing this PR.

2022-02-04 16:50 UTC, closed without merging