Create LogEntryData-bigqueryjobcompleted.json
googleapis/google-cloudevents pull request #314
Opened 2022-01-11 16:37 UTC by minyu19

Adding more JSON example CloudEvents

2022-01-11 16:55 UTC, jskeet commented
The files in `testdata` aren't expected to be complete CloudEvents - just the payloads.

2022-01-12 12:25 UTC, grant requested changes

2022-01-12 12:25 UTC, grant commented on testdata/google/events/cloud/audit/v1/LogEntryData-bigqueryjobcompleted.json
> +  "data": {
As Jon mentioned, put just the _contents_ of the `"data"` property as the JSON object for this file.

2022-01-14 21:55 UTC, grant requested changes

2022-01-14 21:55 UTC, grant commented on testdata/google/events/cloud/audit/v1/LogEntryData-bigqueryjobcompleted.json
> +  }
Format is off, there should be no space here.

2022-01-14 22:51 UTC, grant approved these changes
Approved

2022-01-14 22:51 UTC, grant commented on testdata/google/events/cloud/audit/v1/LogEntryData-bigqueryjobcompleted.json
> +    "insertId": "jpllvgecd7bx",
I can't tell if 2 space indentation is here or more. Should be 2 spaces.

2022-01-20 19:50 UTC, ace-n approved these changes

2022-01-27 19:34 UTC, merged